services:
  energyplus-app:
    build: .
    container_name: energyplus_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1